export const Lang = {
  Danish: 'da',
  German: 'de',
  'English, UK': 'en-GB',
  'English, US': 'en-US',
  Spanish: 'es-ES',
  French: 'fr',
  Croatian: 'hr',
  Italian: 'it',
  Lithuanian: 'lt',
  Hungarian: 'hu',
  Dutch: 'nl',
  Norwegian: 'no',
  Polish: 'pl',
  'Portuguese, Brazilian': 'pt-BR',
  'Romanian, Romania': 'ro',
  Finnish: 'fi',
  Swedish: 'sv-SE',
  Vietnamese: 'vi',
  Turkish: 'tr',
  Czech: 'cs',
  Greek: 'el',
  Bulgarian: 'bg',
  Russian: 'ru',
  Ukrainian: 'uk',
  Hindi: 'hi',
  Thai: 'th',
  'Chinese, China': 'zh-CN',
  'Chinese, Taiwan': 'zh-TW',
  Korean: 'ko',
};
